version: "3"
services:
  dev:
    image: www.lastsweetop.com:5000/godev
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - $PWD:/root/app
